theme: jekyll-theme-minimal
title: William La Cava
description: "I’m a postdoctoral fellow at the University of Pennsylvania in the Institute for Biomedical Informatics (IBI). I mostly develop population-based ML and RL methods."
