theme: jekyll-theme-minimal
title: William La Cava
description: "I’m a faculty member in the Computational Health Informatics Program at Boston Children's Hospital and Harvard Medical School. I develop machine learning methods for fair and interpretable clinical care."
url: https://cavalab.org
